version: '2'

volumes:
  mavendata:
  intellijdata:
  javadata:

services:

  ide:
    build: ide
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.ssh:/home/developer/.ssh
      - ${HOME}/.gnupg:/home/developer/.gnupg
      - ${HOME}/.gitconfig:/home/developer/.gitconfig
      - ${HOME}/.IntelliJIdea/config:/home/developer/.IntelliJIdea/config
      - ${HOME}/.IntelliJIdea/plugins:/home/developer/.IntelliJIdea/plugins
      - intellijdata:/home/developer/.IntelliJIdea/system
      - mavendata:/home/developer/.m2/repository
      - javadata:/home/developer/.java
      - ..:/home/developer/src/
    environment:
      - DISPLAY
      - LANG
      - LANGUAGE
      - TERM
      - TZ=Europe/Paris
    ports:
      - "8080-8090:8080-8090"
    tty: true
